In [1]:
import numpy as np

In [2]:
# Une liste de listes est transformée en un tableau multi-dimensionnel
test = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(test)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [7]:
test1 = np.arange(0,5,1)
test2 = np.linspace(0,4,5)
print(test1,test2)

[0 1 2 3 4] [0. 1. 2. 3. 4.]


In [22]:
test1 = np.random.random((3,3))
test2 = np.random.randint((3,3))
test3 = np.random.normal((3,3))
print(test3)

[3.05091639 2.278476  ]


In [41]:
np.random.seed(0)
x1 = np.random.randint((12,12,12,12,12,12))
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)
print(x1)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int64
[ 5  0  3 11  3  7]


In [43]:
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2,x2[0,1])

# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

[ 5  3  3 11  3  7]
5
7
[[7 8 1 5]
 [9 8 9 4]
 [3 0 3 5]] 8
[   5 1000    3   11    3    7]
[ 5  3  3 11  3  7]


In [44]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[ 5  3  3 11  3]
[7]
[5 3 3]


In [45]:
x1[::-1]

array([ 7,  3, 11,  3,  3,  5])

In [120]:
print(x2)

x2[0,:]

[[7 8 1 5]
 [9 8 9 4]
 [3 0 3 5]]


array([7, 8, 1, 5])

In [91]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [92]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

[1.         0.33333333 0.25       0.11111111 0.5       ]
3.51 s ± 209 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [93]:
%timeit (1.0 / tableau_large)

4.27 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [94]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [95]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [104]:
x = np.random.rand(3,3)
print(x)

np.where(x > 0.5)

[[0.73882912 0.97343133 0.04370114]
 [0.75900897 0.13531095 0.88282561]
 [0.3126663  0.49555108 0.9552979 ]]


(array([0, 0, 1, 1, 2]), array([0, 1, 0, 2, 2]))

In [107]:
L = np.random.random(100)
print(np.sum(L))
print(np.min(L))
print(np.max(L))

46.193192464628325
0.0031533459288014543
0.999635071159728


In [108]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

372 ms ± 115 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
957 µs ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
M = np.random.randint(12,size=(3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))
print("Les sommes des lignes de M: ", M.sum(axis=1))

[[ 2  4  0  8]
 [10  7  7  9]
 [ 7  7  9  3]]
La somme de tous les éléments de M:  73
Les sommes des colonnes de M:  [19 18 16 20]
Les sommes des lignes de M:  [14 33 26]


In [129]:
#np.std pour ecart type
#np.argmin pour l'index de l'element minimum
#np.percentile pour els stat sur les elements
np.percentile(M,20)

3.2

In [133]:
a = np.arange(3)
print('a est:', a)
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
print('b est:',b)
a+b
print('a+b est:',a+b)

a est: [0 1 2]
b est: [[0]
 [1]
 [2]]
a+b est: [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [143]:
np.array([[0],[1],[2]])

array([[0],
       [1],
       [2]])